### ISSUE TITLE
Другой инструмент

### ISSUE THREAD

**Issue by makc-ar** [flatz/gttool#1]
Здравствуй, мы переносим локализацию на PS4 игры Bioshock Infinite, но файлы локализации там в .bin файлах https://www63.zippyshare.com/v/YEnPQLak/file.html. У тебя остался этот инструмент http://forum.xentax.com/viewtopic.php?p=93368#p93368?  Сможешь создать ветку на github?

**Comment by flatz** [comment]
Привет. Вот исходники утилиты (как-то делал PS4 порт для Trap`а), но не помню, сейчас они в рабочем состоянии или нет: https://github.com/flatz/bioshock
Думаю, что должно работать.
P.S. Пиши в тот репозиторий, если что.
